version: '3.9'
networks:
  app-network:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: shop-backend
    command: python manage.py runserver 0.0.0.0:8000 --settings=config.settings.local
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - minio
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.frontend
    container_name: shop-frontend
    command: sh -c "rm -rf node_modules && npm install --include=optional && npm run dev"
    volumes:
      - ../frontend:/frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://146.255.188.248:8000/api
      - CHOKIDAR_USEPOLLING=true
    platform: linux/amd64
    networks:
      - app-network

  db:
    image: postgres:15
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

  minio:
    image: minio/minio:RELEASE.2023-05-04T21-44-30Z
    container_name: shop-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    networks:
      - app-network

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: listen --api-key sk_test_51ROE3JPOV9fDpeeQjdXrjbcSwi4bJ7CU7HYDuoHm9HOmfqqgFm2KqjvIdWzuZY5ABP8yfRiHkS93KPymrIGWUpgB00xKDdl0So --forward-to http://146.255.188.248:8000/api/shop/stripe/webhook
    depends_on:
      - web
    networks:
      - app-network

volumes:
  pgdata:
  minio-data: