# Generated by Django 5.1.7 on 2025-05-24 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
